apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2

  instanceProfile: karpenter-node-eks-karpenter-demo
  # role: arn:aws:iam::123456789012:role/karpenter-node-eks-karpenter-demo

  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: eks-karpenter-demo

  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: eks-karpenter-demo

  tags:
    karpenter.sh/discovery: eks-karpenter-demo
