apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2

  role: karpenter-node-eks-karpenter-demo

  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: eks-karpenter

  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: eks-karpenter

  tags:
    karpenter.sh/discovery: eks-karpenter
