apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
  namespace: karpenter
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  amiFamily: AL2023  
  role: "karpenter-node-eks-karpenter-demo"  

  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: eks-karpenter-demo

  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: eks-karpenter-demo

  tags:
    karpenter.sh/discovery: eks-karpenter-demo