apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: spot
  
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 30s
  
  limits:
    cpu: "200"
    memory: 400Gi
  
  template:
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
        
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values: ["t3", "t3a", "m5", "m5a", "c5", "c5a"]
        
        - key: karpenter.k8s.aws/instance-size
          operator: NotIn
          values: ["nano", "micro", "metal", "24xlarge", "32xlarge"]
        
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
      
      taints: []
      
      kubelet:
        maxPods: 110