apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: spot
spec:
  disruption:
    consolidationPolicy: WhenUnderutilized
    consolidateAfter: 30s

  limits:
    cpu: "1000"

  template:
    spec:
      nodeClassRef:
        name: default

      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]

        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
