apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-config
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/abani-rautray/terraform-eks-karpenter-gitops.git
    targetRevision: HEAD
    path: gitops/karpenter

  destination:
    server: https://kubernetes.default.svc
    # namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
    - group: karpenter.sh
      kind: NodePool
      jqPathExpressions:
      - .status
      - .metadata.annotations
      - .metadata.generation
      - .spec.template.metadata

    - group: karpenter.k8s.aws
      kind: EC2NodeClass
      jqPathExpressions:
      - .status
      - .metadata.annotations
      - .metadata.generation
      - .spec.template.metadata